USE [EventManagementSystem];

INSERT INTO Notifications (User_ID, Content, Read_Status, Notification_Date)
VALUES 
(188, 'Reminder: Your ticket for the Summer Music Festival is confirmed. Don’t miss it!', 'Unread', GETDATE()),
(189, 'New speaker announced for the Tech Innovators Conference. Check it out on the event page.', 'Unread', GETDATE()),
(190, 'Exclusive VIP access granted to you for Art Expo 2024. Enjoy the special tour!', 'Unread', GETDATE()),
(191, 'Your registration for the Healthy Living Expo is confirmed. We look forward to seeing you!', 'Unread', GETDATE()),
(192, 'Check out the latest international food trends at the upcoming International Food Festival.', 'Unread', GETDATE()),
(193, 'Reminder: Business Leaders Summit is just around the corner. Prepare for key discussions.', 'Unread', GETDATE()),
(194, 'Special seating available for Sports Championship 2024. Secure your spot today.', 'Unread', GETDATE()),
(195, 'Your participation in the Global Education Forum is confirmed. Get ready for the discussions ahead.', 'Unread', GETDATE()),
(196, 'Reminder: Innovative Startups Fair begins tomorrow. Don’t miss out on innovative projects.', 'Unread', GETDATE()),
(197, 'Join us for a unique opportunity at the Music and Arts Fundraiser next week.', 'Unread', GETDATE()),
(198, 'New event alert: Digital Marketing Workshop is now open for registration!', 'Unread', GETDATE()),
(199, 'VIP seats available for the Culinary Arts Experience. Book yours today.', 'Unread', GETDATE()),
(200, 'Reminder: The Art and Technology Exhibition is live this weekend. Don’t miss it!', 'Unread', GETDATE()),
(201, 'Important update: Corporate Leadership Forum postponed to a later date.', 'Unread', GETDATE()),
(202, 'Join us at the Startup Pitch Day for exciting startup pitches and investment opportunities.', 'Unread', GETDATE()),
(203, 'Your registration for the International Art Auction is confirmed. Get ready to bid!', 'Unread', GETDATE()),
(204, 'Tech Trends Seminar is coming soon. Stay ahead of the curve in tech developments.', 'Unread', GETDATE()),
(205, 'Reminder: World Food and Drink Show starts in two days. Enjoy the global culinary experience.', 'Unread', GETDATE()),
(206, 'Fitness and Wellness Weekend is almost here! Prepare for fitness challenges and wellness tips.', 'Unread', GETDATE()),
(207, 'Important reminder: Your registration for the Education for the Future Summit is confirmed.', 'Unread', GETDATE()),
(208, 'Special discount available for the next event. Check the latest promotions on our website.', 'Unread', GETDATE()),
(209, 'Exclusive ticket offer for loyal attendees: Book your next event ticket now for a 10% discount!', 'Unread', GETDATE()),
(210, 'Your seat is reserved for the Art Expo 2024. We can’t wait to see you there!', 'Unread', GETDATE()),
(211, 'Reminder: Secure your place at the upcoming Digital Marketing Workshop to enhance your skills.', 'Unread', GETDATE()),
(212, 'Reminder: The International Food Festival will feature a surprise guest chef. Stay tuned for updates!', 'Unread', GETDATE()),
(213, 'Get ready for the Sports Championship 2024. Participate and compete in exciting activities.', 'Unread', GETDATE()),
(214, 'Important update: The Healthy Living Expo has added new workshops. Check them out now!', 'Unread', GETDATE()),
(215, 'Global Education Forum starts soon. Prepare for enriching discussions and networking opportunities.', 'Unread', GETDATE()),
(216, 'New workshop announced for the Tech Innovators Conference. Register now to secure your spot.', 'Unread', GETDATE()),
(217, 'Last chance to register for the Music and Arts Fundraiser! Join us in supporting the cause.', 'Unread', GETDATE()),
(218, 'You’re invited to an exclusive preview event for the upcoming Art and Technology Exhibition.', 'Unread', GETDATE());
